---
title: 'OnlyFans Millionaires: Site Says 5,076 Creators Have Earned More Than $1 Million to Date'
domain: online-video
tier: 01-Raw
entry_id: online-video-general-onlyfans-millionaires-site-says-5-076-creators-have-earned-more-than-1-million-to-date
source_url: https://variety.com/2026/digital/news/onlyfans-millionaires-creators-earned-more-than-1-million-1236842444/
source_type: rss
source_platform: variety
collected_at: '2026-08-25T15:30:46+00:00'
summary: OnlyFans reports that 5,076 creators have earned over $1 million on the platform since its launch in 2016. The company
  takes a 20% cut of gross revenue generated by its creators.
tags: []
quality_tier: 2
relevance_score: 0.0
dedup_status: duplicate
source_score: 70.0
language: en
user_id: ''
version: 1
previous_version: 0
supersedes: ''
trace_id: 60d9132d-42b2-4afc-80c6-1a6cabac6888
quality_flags:
  G0-SchemaIntegrity: false
  G1-SourceAuthority: false
  G1-TosCompliance: false
  G2-Dedup: true
  G3-RelevanceScoring: true
  G4-SummaryFactual: false
tos_compliant: true
tos_classification: open
---

## Original Content
A sizable bunch of top OnlyFans creators have taken home seven-figure checks from the fan-monetization site. Since the 2016 launch of OnlyFans, which is known for its porn-friendly policies, 5,076 creators have made over $1 million on the platform, the company said Tuesday. In total, OnlyFans &#8212; which takes a 20% cut of gross revenue [&#8230;]

## Summary
OnlyFans reports that 5,076 creators have earned over $1 million on the platform since its launch in 2016. The company takes a 20% cut of gross revenue generated by its creators.

## Key Points
- 5,076 OnlyFans creators have earned more than $1 million on the platform
- OnlyFans was launched in 2016 and is known for its porn-friendly policies
- The platform takes a 20% cut of gross revenue from creators
- OnlyFans operates as a fan-monetization site


## Entities
- **OnlyFans** (org, relevance=)
- **$1 Million** (concept, relevance=)
